spring:
  application:
    name: boki-spring-actuator2

management:
#  server:
#    port: 9292
#    base-path: '/manage'
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
#      show-components: always


info:
  app:
    name: boki-actuator
    company: bk

logging:
  level:
    com.boki.bokispringactuator2.controller: debug
