@protocol = http
@myhost = localhost:8080
@target = {{protocol}}://{{myhost}}
@actuator = {{protocol}}://{{myhost}}/actuator
// @no-log
// @no-cookie-jar

### Actuator endpoints
# actuator 접속 엔드포인트
GET {{actuator}}

### Shutdown
# 서버 강제 종료
POST {{actuator}}/shutdown

### Health endpoint
GET {{actuator}}/health

### Info endpoint
GET {{actuator}}/info

### Call Log
GET {{target}}/log

### Logger endpoint
GET {{actuator}}/loggers

### Change Logger Level
# 로그 레벨 실시간 변경
POST {{actuator}}/loggers/com.boki.bokispringactuator2.controller
Content-Type: application/json

{
  "configuredLevel": "TRACE"
}

### HTTP request/response memory endpoint
GET {{actuator}}/httpexchanges

### Metrics endpoint
GET {{actuator}}/metrics

### JVM Tag Filter
# tag=key:value로 필터링
GET {{actuator}}/metrics/jvm.memory.used?tag=area:heap

### HTTP Request Count
GET {{actuator}}/metrics/http.server.requests

### HTTP Request Count Tag Filter(/log)
GET {{actuator}}/metrics/http.server.requests?tag=uri:/log

### HTTP Request Count Tag Filter(/log and 200)
GET {{actuator}}/metrics/http.server.requests?tag=uri:/log&tag=status:200
